apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.container.image }}
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: {{ .Values.env.DB_HOST }}
        - name: DB_USER
          value: {{ .Values.env.DB_USER }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: database-postgresql
              key: postgres-password
        - name: DB_NAME
          value: {{ .Values.env.DB_NAME }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels: 
    app: backend
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: backend
  type: ClusterIP